language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t maxpicky/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true maxpicky/docker-react npm run test -- --coverage
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-151124369481"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY