language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -t maxpicky/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true maxpicky/docker-react npm run test -- --coverage